### ISSUE TITLE
2.2 Example: Authorization header

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-vapid#10]
2.2. Example

```
Authorization: Bearer
```

_Is this intended to be WebPush rather than OAuth Bearer (RFC6750)?_

**Comment by martinthomson** [comment]
Actually, @costinm asked whether we should just use Bearer and I couldn't think of a reason not to.  Though I had originally looked at Bearer and decided not to use it, I don't remember the reason it was unsuitable.  I think that Bearer is adequate and so will correct.

**Comment by brianraymor** [comment]
Based on #18, proceeding with WebPush rather than Bearer.
