### ISSUE TITLE
VAPID claim should include optional extra data field

### ISSUE THREAD

**Issue by jrconlin** [webpush-wg/webpush-vapid#24]
As noted in the arguments of #23, there is a need for an "extra data" field which would be used by the parties using the VAPID claims. This data would contain information useful to the publisher of the claim (e.g. the originating server ID, transaction ID, or other possibly VAPID consumer opaque data).

This extra data ("vapid-ext" ?) field would allow consistent, predictable definition rather than a set of 'one-offs' that may be difficult to find or ignored by operators.

**Comment by martinthomson** [comment]
Started thread: https://mailarchive.ietf.org/arch/msg/webpush/Z1PhP26WL4k7KY5QOwIznBsk8kc
